In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>',x.size)
print('dimension wise elements=>',x.shape)
print('dimension count',x.ndim)

[2 3 5 1 2 4]
total elements => 6
dimension wise elements=> (6,)
dimension count 1


In [6]:
y = np.array([[2,3,5],[3,2,1]])
print(y)
print('total elements =>',y.size)
print('dimension wise elements=>',y.shape)
print('dimension count',y.ndim)

[[2 3 5]
 [3 2 1]]
total elements => 6
dimension wise elements=> (2, 3)
dimension count 2


In [9]:
x= [1,2,3]
z = np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)

shape (3, 3, 3)
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [16]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [17]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [20]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [27]:
a = np.linspace(1, 1000, 11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [33]:
d = np.random.randint(1,6,(10,10))

In [34]:
print(d)

[[3 1 5 5 4 1 2 4 2 2]
 [2 5 5 5 5 5 5 3 1 3]
 [3 4 1 3 4 2 1 4 4 1]
 [2 3 4 5 2 3 3 1 3 5]
 [1 2 5 2 2 3 1 5 4 2]
 [2 2 1 1 5 3 5 5 4 1]
 [1 4 3 5 3 1 4 3 3 4]
 [4 1 4 1 2 1 1 3 1 4]
 [1 5 5 3 5 3 3 4 1 1]
 [1 2 3 1 1 4 1 5 3 4]]


In [37]:
d[-1]

array([1, 2, 3, 1, 1, 4, 1, 5, 3, 4])

In [42]:
d[0,0] # d[0][0]

3

In [45]:
d[3,5]

3

In [46]:
d[:, 0] # all rows of column idx 0

array([3, 2, 3, 2, 1, 2, 1, 4, 1, 1])

In [47]:
d[:, -3]

array([4, 3, 4, 1, 5, 5, 3, 3, 4, 5])

In [48]:
d[:5, 2] # first five rows of column idx 2

array([5, 5, 1, 4, 5])

In [49]:
d[:5, :5] # ?

array([[3, 1, 5, 5, 4],
       [2, 5, 5, 5, 5],
       [3, 4, 1, 3, 4],
       [2, 3, 4, 5, 2],
       [1, 2, 5, 2, 2]])

In [52]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))
print(x,'\n', y)

[[6 7 1]
 [8 7 2]
 [2 2 9]] 
 [[6 1 7]
 [1 7 6]
 [1 8 3]]


In [53]:
x + y

array([[12,  8,  8],
       [ 9, 14,  8],
       [ 3, 10, 12]])

In [54]:
x - y

array([[ 0,  6, -6],
       [ 7,  0, -4],
       [ 1, -6,  6]])

In [55]:
x + 10

array([[16, 17, 11],
       [18, 17, 12],
       [12, 12, 19]])

In [56]:
x - 10

array([[-4, -3, -9],
       [-2, -3, -8],
       [-8, -8, -1]])

In [57]:
x * 10

array([[60, 70, 10],
       [80, 70, 20],
       [20, 20, 90]])

In [58]:
np.dot(x,y)

array([[ 44,  63,  87],
       [ 57,  73, 104],
       [ 23,  88,  53]])

In [59]:
np.matmul(x,y)

array([[ 44,  63,  87],
       [ 57,  73, 104],
       [ 23,  88,  53]])

In [60]:
np.multiply(x,y)

array([[36,  7,  7],
       [ 8, 49, 12],
       [ 2, 16, 27]])

In [61]:
x * y

array([[36,  7,  7],
       [ 8, 49, 12],
       [ 2, 16, 27]])

In [62]:
np.cross(x,y)

array([[ 48, -36, -36],
       [ 28, -46,  49],
       [-66,   3,  14]])

In [64]:
np.hstack([x,y])

array([[6, 7, 1, 6, 1, 7],
       [8, 7, 2, 1, 7, 6],
       [2, 2, 9, 1, 8, 3]])

In [65]:
np.vstack([x,y])

array([[6, 7, 1],
       [8, 7, 2],
       [2, 2, 9],
       [6, 1, 7],
       [1, 7, 6],
       [1, 8, 3]])

In [72]:
np.append(x,y,axis=0)

array([[6, 7, 1],
       [8, 7, 2],
       [2, 2, 9],
       [6, 1, 7],
       [1, 7, 6],
       [1, 8, 3]])

In [73]:
x.max()

9

In [74]:
x.max(axis=0)

array([8, 7, 9])

In [76]:
x.min(axis=1)

array([1, 2, 2])

In [78]:
x.flatten()

array([6, 7, 1, 8, 7, 2, 2, 2, 9])

In [81]:
d[d > 3] # boolean filter

array([5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 5, 5, 5, 5, 4, 5, 5,
       5, 4, 4, 5, 4, 4, 4, 4, 4, 5, 5, 5, 4, 4, 5, 4])

In [82]:
d[d==1] # give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])